export const browserCoreExamples = [
  "atomicbot browser status",
  "atomicbot browser start",
  "atomicbot browser stop",
  "atomicbot browser tabs",
  "atomicbot browser open https://example.com",
  "atomicbot browser focus abcd1234",
  "atomicbot browser close abcd1234",
  "atomicbot browser screenshot",
  "atomicbot browser screenshot --full-page",
  "atomicbot browser screenshot --ref 12",
  "atomicbot browser snapshot",
  "atomicbot browser snapshot --format aria --limit 200",
  "atomicbot browser snapshot --efficient",
  "atomicbot browser snapshot --labels",
];

export const browserActionExamples = [
  "atomicbot browser navigate https://example.com",
  "atomicbot browser resize 1280 720",
  "atomicbot browser click 12 --double",
  'atomicbot browser type 23 "hello" --submit',
  "atomicbot browser press Enter",
  "atomicbot browser hover 44",
  "atomicbot browser drag 10 11",
  "atomicbot browser select 9 OptionA OptionB",
  "atomicbot browser upload /tmp/atomicbot/uploads/file.pdf",
  'atomicbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "atomicbot browser dialog --accept",
  'atomicbot browser wait --text "Done"',
  "atomicbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "atomicbot browser console --level error",
  "atomicbot browser pdf",
];
